name: Make CardData

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  make-carddata:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Git Config
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-keyscan gitee.com >> ~/.ssh/known_hosts

    - name: Restore pics cache
      uses: actions/cache/restore@v4
      with:
        path: pics
        key: pics

    - name: Clone repository
      env:
        SOURCE_REPO: ${{ secrets.PICS_REPO }}
      run: |
        if [ -d pics ]; then
          cd pics
          git remote set-url origin "$SOURCE_REPO"
          git remote update --prune
          echo "repo_changed=true" >> $GITHUB_OUTPUT
        else
          git clone "$SOURCE_REPO" pics --depth 1
          cd pics
          git pull >> file.txt
          grep -qwE "Already up to date." file.txt
          if [ $? -eq 0 ]; then
            echo "repo_changed=false" >> $GITHUB_OUTPUT
          else
            echo "repo_changed=true" >> $GITHUB_OUTPUT
          fi
          rm file.txt
        fi

    - name: Install Rust
      if: ${{ steps.check.outputs.repo_changed == 'true' }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.95.0

    - name: Restore mirror cache
      if: ${{ steps.check.outputs.repo_changed == 'true' }}
      uses: actions/cache/restore@v4
      with:
        path: core-wasm/target/release
        key: Rust

    - name: Hashing hdarts
      if: ${{ steps.check.outputs.repo_changed == 'true' }}
      run: |
        cd core-wasm
        wget https://github.com/mycard/ygopro-database/raw/refs/heads/master/locales/zh-CN/cards.cdb
        cargo run --release ../pics/arts cards.cdb ../public/card_data
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add ../public/card_data
        git commit -m "update card_data"
        git push

    - name: Delete previous cache
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh cache delete "pics" || true
        gh cache delete "Rust" || true

    - name: Save rust cache
      if: ${{ steps.check.outputs.repo_changed == 'true' }}
      uses: actions/cache/save@v4
      with:
        path: core-wasm/target/release
        key: Rust

    - name: Save pics cache
      uses: actions/cache/save@v4
      with:
        path: pics
        key: pics
